// Third-party notices (LEG-014): the open-source packages the site uses,
// their licences, and their licence and notice files, which the minified
// bundles don't carry.
//
//   npm run licenses           rewrites lib/licenses.json and public/licenses.txt
//   npm run licenses -- --check  fails if either is out of date (CI runs this)
//
// Which packages: package.json's dependencies (not devDependencies) and
// everything they pull in, resolved through package-lock.json the way Node
// finds a module: dependencies, optional ones that are installed, and peers
// that aren't optional. Also each package app/globals.css imports: tailwindcss
// and shadcn are devDependencies, but CSS from them is compiled into the
// stylesheet the site serves. Only the package itself, not what it pulls in,
// which is build tooling (for shadcn, its command-line tool's).
// Left out: platform-specific builds (a lockfile entry with os or cpu), such
// as Next's compiler and sharp's image library. They run on the build and
// server machines only, never in a browser, and which ones npm installs
// depends on the machine, so leaving them out keeps the output the same
// wherever this runs.
//
// The text comes from each package as installed: run `npm ci` first.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const read = (p) => readFileSync(join(root, p), "utf8");
const lock = JSON.parse(read("package-lock.json")).packages;
const own = JSON.parse(read("package.json"));

/** The lockfile key Node would load `name` from, asked for by the package at `from`. */
function resolve(from, name) {
  let dir = from;
  for (;;) {
    const key = dir ? `${dir}/node_modules/${name}` : `node_modules/${name}`;
    if (lock[key]) return key;
    if (!dir) return null;
    const up = dir.lastIndexOf("/node_modules/");
    dir = up < 0 ? "" : dir.slice(0, up);
  }
}

const shipped = new Set();
function visit(from, name, optional) {
  const key = resolve(from, name);
  if (!key) {
    if (optional) return;
    throw new Error(`${name} (needed by ${from || "package.json"}) isn't in package-lock.json`);
  }
  const entry = lock[key];
  if (entry.os || entry.cpu || shipped.has(key)) return;
  shipped.add(key);
  for (const dep of Object.keys(entry.dependencies ?? {})) visit(key, dep, false);
  for (const dep of Object.keys(entry.optionalDependencies ?? {})) visit(key, dep, true);
  // An optional peer is the app's choice, not the package's: if the app wants
  // it, it's in package.json's dependencies (or pulled in by one of them).
  for (const dep of Object.keys(entry.peerDependencies ?? {})) {
    if (!entry.peerDependenciesMeta?.[dep]?.optional) visit(key, dep, false);
  }
}
for (const dep of Object.keys(own.dependencies ?? {})) visit("", dep, false);

// `@import "pkg"` or `@import "pkg/file.css"` (not relative paths or url()).
const cssImports = [...read("app/globals.css").matchAll(/@import\s+["']([^"'./][^"']*)["']/g)].map(([, spec]) =>
  spec.split("/").slice(0, spec.startsWith("@") ? 2 : 1).join("/"),
);
for (const name of cssImports) {
  const key = resolve("", name);
  if (!key) throw new Error(`${name} (imported by app/globals.css) isn't in package-lock.json`);
  shipped.add(key);
}

const LICENCE_FILE = /^(licen[cs]e|copying|notice)\b/i;
const packages = new Map();
for (const key of shipped) {
  const pkg = JSON.parse(read(`${key}/package.json`));
  const id = `${pkg.name}@${pkg.version}`;
  if (packages.has(id)) continue;
  const declared = typeof pkg.license === "string" ? pkg.license : (pkg.license?.type ?? null);
  const files = readdirSync(join(root, key))
    .filter((f) => LICENCE_FILE.test(f) && statSync(join(root, key, f)).isFile())
    .sort()
    .map((f) => ({ file: f, text: read(`${key}/${f}`).replace(/\r\n?/g, "\n").trim() }));
  const author = typeof pkg.author === "string" ? pkg.author : (pkg.author?.name ?? null);
  packages.set(id, { name: pkg.name, version: pkg.version, license: declared, author, files });
}
const list = [...packages.values()].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : a.version < b.version ? -1 : 1));

const json =
  JSON.stringify(
    list.map(({ name, version, license }) => ({ name, version, license })),
    null,
    2,
  ) + "\n";

const rule = "=".repeat(72);
const txt =
  [
    "Open-source software in the RowTech site and dashboard",
    "",
    `The RowTech site and dashboard use the ${list.length} packages below, in the code they`,
    "run and in their stylesheet. Tools that only build and test the site aren't",
    "listed, and neither are the machine-specific builds of Next.js's compiler and",
    "sharp's image library.",
    "Each one's license and notice files follow its name, as the package ships them.",
    "Generated by scripts/licenses.mjs from package-lock.json.",
    ...list.flatMap((p) => [
      "",
      rule,
      `${p.name} ${p.version}`,
      `License: ${p.license ?? "not stated in its package.json"}`,
      rule,
      ...(p.files.length
        ? p.files.flatMap((f) => ["", `--- ${f.file} ---`, "", f.text])
        : [
            "",
            "The package ships no license file." + (p.author ? ` Its package.json names its author: ${p.author}.` : ""),
          ]),
    ]),
  ].join("\n") + "\n";

const outputs = [
  ["lib/licenses.json", json],
  ["public/licenses.txt", txt],
];
if (process.argv.includes("--check")) {
  const stale = outputs.filter(([p, body]) => {
    try {
      return read(p) !== body;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`Out of date: ${stale.map(([p]) => p).join(", ")}. Run npm run licenses and commit the result.`);
    process.exit(1);
  }
  console.log(`Third-party notices are up to date (${list.length} packages).`);
} else {
  for (const [p, body] of outputs) writeFileSync(join(root, p), body);
  console.log(`Wrote ${outputs.map(([p]) => p).join(" and ")} (${list.length} packages).`);
}
